# Generated by Django 5.2.3 on 2025-07-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_rename_recovery_mail_verification_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
